## https://nlu.rasa.com/0.12.2/pipeline.html

language: "en"

pipeline:
- name: "nlp_spacy"
  model: "xx"
  case_sensitive: False
- name: "tokenizer_spacy"

- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_entity_featurizer_regex"
- name: "feature.CountVectorsFeaturizer"
- name: "intent_classifier_tensorflow_embedding"
  epochs: 1000
  droprate: 0.0

